service: chapter7-resources
frameworkVersion: ">=4.0.0"
plugins:
  - serverless-dotenv-plugin
custom:
  region: ${env:AWS_DEFAULT_REGION, 'ap-northeast-2'}
  accountid: ${env:AWS_ACCOUNT_ID}
  trainingbucket: ${env:CHAPTER7_PIPELINE_TRAINING_BUCKET}
  dotenv:
    path: ../../.env

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION, 'ap-northeast-2'}

resources:
  Resources:
    TrainingBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.trainingbucket}
        AccessControl: Private

