service: chapter4users
frameworkVersion: ">=1.30.0"
custom:
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  accountid: ${env:AWS_ACCOUNT_ID}
  stage: ${self:provider.stage}
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}

resources:
  - ${file(./user-pool.yml)}
  - ${file(./identity-pool.yml)}

